version: '3.7'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - HOST=${HOST}
      - MONGO_URI=mongodb://mongo:27017/currency_tracker
    depends_on:
      - mongo

  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: